### ISSUE TITLE
HI, I have this error

### ISSUE THREAD

**Issue by maalvarez82** [riedayme/Kurteyki#1]
I try login in http://localhost/Kurteyki/app and the web shows this error

A Database Error Occurred
Error Number: 1055

Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'kurteyki.tb_site_visitor.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

SELECT COUNT(*) AS `numrows` FROM ( SELECT `id` FROM `tb_site_visitor` GROUP BY `ip`, DATE(date) ) CI_count_all_results

Filename: D:/laragon/www/Kurteyki/system/database/DB_driver.php

Line Number: 691

**Comment by riedayme** [comment]
in advance I am grateful for what you told

it looks like an error is due to differences in the version of the application being run.

you try to adjust the application used with what I used when making this.

I use xampp with php version 7.3 you can download it here: 
[https://www.apachefriends.org/xampp-files/7.3.16/xampp-windows-x64-7.3.16-1-VC15-installer.exe](https://www.apachefriends.org/xampp-files/7.3.16/xampp-windows-x64-7.3.16-1-VC15-installer.exe)

**Comment by maalvarez82** [comment]
it's working, thanks
